begin;

create table public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer jsonb not null,
  "order" integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index faqs_order_idx on public.faqs ("order");

alter table public.faqs enable row level security;

create policy "Public FAQs are readable"
  on public.faqs
  for select
  to anon, authenticated
  using (true);

commit;
